### ISSUE TITLE
Standard league

### ISSUE THREAD

**Issue by Tuanitoss** [trevorm4/HeistGemPricechecker#1]
Hi, love the pricechecker, but I wanted to change the api to standard league and I would probably need to change it in the .exe file so I was just wondering if you could add a function to change the league. Thanks

**Comment by trevorm4** [comment]
https://github.com/trevorm4/HeistGemPricechecker/releases/tag/v3

Added support for this in the latest release, you will just need to change the league line in the AHK file to Standard
