### ISSUE TITLE
Error when pushing F3

### ISSUE THREAD

**Issue by Neltisen** [trevorm4/HeistGemPricechecker#2]
Traceback (most recent call last):
  File "heist_ocr.py", line 1, in <module>
ModuleNotFoundError: No module named 'pytesseract'

**Comment by Neltisen** [comment]
As an additional information, v3 works fine. Error appears in Kalandra updated version after changing to Standard

**Comment by Neltisen** [comment]
And there's another when scanning Anomalous Rolling Magma:

Traceback (most recent call last):
  File "heist_ocr.py", line 124, in <module>
  File "heist_ocr.py", line 119, in print_output
ValueError: min() arg is an empty sequence

**Comment by trevorm4** [comment]
Did you download pricechecker.zip that has the dist folder and the ahk script?

**Comment by trevorm4** [comment]
Also, it isn't really meant to be functional until the league launches today as it has gems that aren't currently in the game etc. I'll test it out myself in next few days when I get to  running blueprints and hopefully fix it then if it is still broken.

**Comment by trevorm4** [comment]
Oops, I messed up the building a bit. I just updated the kalandra release, let me know if it fixes it for you. (forgot to activate my virtual environment so all the libraries were missing)
